FROM docker.stirlingpdf.com/stirlingtools/stirling-pdf:2.14.3

ENV PORT=8080
ENV SERVER_PORT=8080
ENV SECURITY_ENABLELOGIN=true
ENV SYSTEM_DEFAULTLOCALE=en-US
ENV SYSTEM_GOOGLEVISIBILITY=false

EXPOSE 8080
